CHECK_FOR_WARNINGS = 'check_for_warnings'
HAS_COLUMN_NAMES = 'has_column_names'
HED_XML_PATH = 'hed_path'
REQUIRED_TAG_COLUMNS = 'required_tag_columns'
SPREADSHEET_PATH = 'spreadsheet_path'
TAG_COLUMNS = 'tag_columns'
WORKSHEET_NAME = 'worksheet'
