version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

# plugins:
#   eslint:
#     enabled: true
#     channel: "eslint-6"
#   rubocop:
#     enabled: true
#     channel: "rubocop-0-79"

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/*__init__.py"
- "**/*setup.py"
- "**/static/"
- "**/constants/"
- "**/deploy_hed/"
- "**/README*"
- "**/.gitignore"
- "**/LICENSE"
- "**/examples/"
- "**/*.yml"
- "**/*.yaml"
- "**/config_template.py"
- "**/*.txt"
- "**/*.html"
- "**/.coveragerc"
- "**/*.md"
- "**/app_factory.py"
- "**/runserver.py"
- "**/*.rst"
- "**/templates/"