CHECK_FOR_WARNINGS = 'check_for_warnings'

COMMAND = 'command'
COMMAND_ASSEMBLE = 'command_assemble'
COMMAND_CONVERT = 'command_convert'
COMMAND_OPTION = 'command_option'
COMMAND_TO_LONG = 'command_to_long'
COMMAND_TO_SHORT = 'command_to_short'
COMMAND_VALIDATE = 'command_validate'

COLUMN_NAMES = 'column_names'
COLUMN_NAMES_TABLE = 'column_names_table'
COLUMN_POSTFIX = '_column'
COLUMN_PREFIX_DICTIONARY = 'column_prefix_dictionary'
COLUMNS_FILE = 'columns_file'
COLUMNS_PATH = 'columns_path'
COLUMNS_DISPLAY_NAME = 'columns_display_name'

DEFS_EXPAND = 'defs_expand'
HAS_COLUMN_NAMES = 'has_column_names'
TAG_COLUMNS = 'tag_columns'
COLUMN_INDICES = 'column_indices'
DOWNLOAD_FILE = 'download_file'

EVENTS = 'events'
EVENTS_DISPLAY_NAME = 'events_display_name'
EVENTS_FILE = 'events_file'
EVENTS_FLASH = 'events_flash'
EVENTS_PATH = 'events_path'
EVENTS_STRING = 'events_string'
EVENTS_SUBMIT = 'events_submit'
EVENTS_SUBMIT_FLASH = 'events_submit_flash'

OTHER_VERSION_OPTION = 'Other'

HEDSTRING = 'hedstring'

JSON_DICTIONARY = 'json_dictionary'
JSON_DISPLAY_NAME = 'json_display_name'
JSON_FILE = 'json_file'
JSON_PATH = 'json_path'
JSON_STRING = 'json_string'
JSON_STRINGS = 'json_strings'

OUTPUT_DISPLAY_NAME = 'output_display_name'

# Schema-specific constants
SCHEMA = 'schema'
SCHEMA_FORM = 'schema_form'
SCHEMA_DISPLAY_NAME = 'schema_display_name'
SCHEMA_FILE = 'schema_file'
SCHEMA_FILE_FLASH = 'schema_file_flash'
SCHEMA_FILE_OPTION = 'schema_file_option'
SCHEMA_FORMAT = 'schema_format'
SCHEMA_PATH = 'schema_path'
SCHEMA_SELECT_FLASH = 'schema_select_flash'
SCHEMA_STRING = 'schema_string'
SCHEMA_SUBMIT = 'schema_submit'
SCHEMA_SUBMIT_FLASH = 'schema_submit_flash'
SCHEMA_UPLOAD_OPTIONS = 'schema_upload_options'
SCHEMA_URL = 'schema_url'
SCHEMA_URL_DISPLAY_NAME = 'schema_url_display_name'
SCHEMA_URL_FLASH = 'schema_url_flash'
SCHEMA_URL_OPTION = 'schema_url_option'
SCHEMA_VERSION = 'schema_version'
SCHEMA_VERSION_LIST = 'schema_version_list'

SERVICE = 'service'

REQUIRED_COLUMN_INDICES = 'required_column_indices'
SPREADSHEET = 'spreadsheet'
SPREADSHEET_DISPLAY_NAME = 'spreadsheet_display_name'
SPREADSHEET_FILE = 'spreadsheet_file'
SPREADSHEET_FLASH = 'spreadsheet_flash'
SPREADSHEET_PATH = 'spreadsheet_path'
SPREADSHEET_STRING = ''
SPREADSHEET_SUBMIT_FLASH = 'spreadsheet_submit_flash'

STRING_INPUT = 'string_input'
STRING_LIST = 'string_list'
STRING_RESULT = 'string_result'

WORKSHEET_NAME = 'worksheet_name'
WORKSHEET_NAMES = 'worksheet_names'
WORKSHEET_SELECT = 'worksheet_select'
WORKSHEET_SELECTED = 'worksheet_selected'


# Type constants
BOOLEAN = 'boolean'
STRING = 'string'
