TEXT_EXTENSION = '.txt'
SPREADSHEET_FILE_EXTENSIONS = ['.xls', '.xlsx', '.txt', '.tsv']
EXCEL_FILE_EXTENSIONS = ['.xls', '.xlsx']
DICTIONARY_FILE_EXTENSIONS = ['.json']
TEXT_FILE_EXTENSIONS = ['.txt', '.tsv']
SCHEMA_WIKI_EXTENSION = '.mediawiki'
SCHEMA_XML_EXTENSION = '.xml'
SCHEMA_EXTENSIONS = [SCHEMA_XML_EXTENSION, SCHEMA_WIKI_EXTENSION]
