ADDITIONAL_EXAMPLES_ROUTE = '/additional-examples'
COMMON_ERRORS = 'common-errors.html'
COMMON_ERRORS_ROUTE = '/common-errors'
HELP_ROUTE = '/help'
HOME_ROUTE = '/'
SUBMIT_ROUTE = '/submit'
SUBMIT_TAG_ROUTE = '/submit_tag'
CONVERSION_ROUTE = '/conversion'
