ADDITIONAL_EXAMPLES_PAGE = 'additional-examples.html'
COMMON_ERRORS_PAGE = 'common-errors.html'
DICTIONARY_VALIDATION_PAGE = 'dictionary.html'
EEG_VALIDATION_PAGE = 'eeg-spreadsheet.html'
HED_TOOLS_HELP_PAGE = 'hed-tools-help.html'
HED_TOOLS_HOME_PAGE = 'hed-tools-home.html'
SCHEMA_PAGE = 'schema.html'
SPREADSHEET_VALIDATION_PAGE = 'spreadsheet.html'
