ROUTE_BLUEPRINT = 'route_blueprint'

ADDITIONAL_EXAMPLES_ROUTE = '/additional-examples'
COMMON_ERRORS_ROUTE = '/common-errors'
DELETE_FILE_ROUTE = '/delete/<filename>'
DICTIONARY_ROUTE = '/dictionary'
DICTIONARY_VALIDATION_SUBMIT_ROUTE = '/dictionary-validation-submit'
DOWNLOAD_FILE_ROUTE = '/download-file/<filename>'

EVENTS_ROUTE = '/events'
EVENTS_VALIDATION_SUBMIT_ROUTE = '/events-validation-submit'
HED_MAJOR_VERSION_ROUTE = '/get-hed-major-versions'
HED_SERVICES_SUBMIT_ROUTE = '/hed-services-submit'
HED_SERVICES_ROUTE = '/hed-services'
HED_TOOLS_HELP_ROUTE = '/hed-tools-help'
HED_TOOLS_HOME_ROUTE = '/'
HED_VERSION_ROUTE = '/get-hed-version'
SCHEMA_ROUTE = '/schema'
SCHEMA_COMPLIANCE_CHECK_SUBMIT_ROUTE = '/schema-compliance-check-submit'
SCHEMA_CONVERSION_SUBMIT_ROUTE = '/schema-conversion-submit'
SPREADSHEET_COLUMN_INFO_ROUTE = '/get-spreadsheet-columns-info'
SPREADSHEET_ROUTE = '/spreadsheet'
SPREADSHEET_VALIDATION_SUBMIT_ROUTE = '/spreadsheet-validation-submit'
WORKSHEET_COLUMN_INFO_ROUTE = '/get-worksheets-info'
