name: CI Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.platform }}
    env:
      UV_SYSTEM_PYTHON: "1"

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv pip install -e .[test]

      - name: Test with unittest
        env:
          HED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m unittest discover tests
