name: Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ruff:
    name: Check for style errors and common problems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Run Ruff linter and formatter check
        run: uvx ruff check . && uvx ruff format --check .
