on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Create work directory
        run: mkdir workdir

      - name: Create virtual environment
        run: uv venv workdir/.venv --python ${{ matrix.python-version }}

      - name: Install package
        run: |
          source workdir/.venv/bin/activate
          uv pip install "$GITHUB_WORKSPACE"

      - name: Run post-installation test
        run: |
          source workdir/.venv/bin/activate
          python -c "from hed.models.hed_string import HedString; print('Import test passed.')"
